### ISSUE TITLE
JWT question

### ISSUE THREAD

**Issue by milosjovac** [manifest/vmq_joseauth#1]
Hi,

Please help me to understand, does this plugin allows user to connect to VerneMQ with JWT provided by 3rd party service (KeyCloak for example) ? 

Thanks!

**Comment by manifest** [comment]
It should work with any JWT. The only required claims are **iss** and **sub**. You should have a key to be able to verify the token and name of the key should follow a name convention described in README. 

You also can change the way how tokens are validated through [verify_options](https://github.com/manifest/jose-erlang) configuration parameter.
